### ISSUE TITLE
AssertionError in pdf2png

### ISSUE THREAD

**Issue by Kampi** [INTI-CMNB/KiDiff#7]
I get the following output when running `kicad-diff.py Old.kicad_pcb New.kicad_pcb --exclude Exclude.txt --cache_dir Cache --keep_pngs -vv`

```
DEBUG:kicad-diff.py:Using cached User.5 layer
DEBUG:kicad-diff.py:Using cached User.6 layer
DEBUG:kicad-diff.py:Using cached User.7 layer
DEBUG:kicad-diff.py:Using cached User.8 layer
DEBUG:kicad-diff.py:Using cached User.9 layer
DEBUG:kicad-diff.py:Executing: bash -c 'convert -density 300 "Cache/6521f80d85529af422c7c0262e6843a2c431338a/0.pdf" -background white -alpha remove -alpha off -threshold 50% -colorspace Gray -resample 150 -depth 8 "Cache/6521f80d85529af422c7c0262e6843a2c431338a/0.png"'
DEBUG:kicad-diff.py:Running ['bash', '-c', 'convert -density 300 "Cache/6521f80d85529af422c7c0262e6843a2c431338a/0.pdf" -background white -alpha remove -alpha off -threshold 50% -colorspace Gray -resample 150 -depth 8 "Cache/6521f80d85529af422c7c0262e6843a2c431338a/0.png"'] returned 1
DEBUG:kicad-diff.py:- StdOut from command: convert-im6.q16: attempt to perform an operation not allowed by the security policy `PDF' @ error/constitute.c/IsCoderAuthorized/421.
convert-im6.q16: no images defined `Cache/6521f80d85529af422c7c0262e6843a2c431338a/0.png' @ error/convert.c/ConvertImageCommand/3229.

Traceback (most recent call last):
  File "/usr/bin/kicad-diff.py", line 795, in <module>
    output_pdf = DiffImages(old_file_hash, new_file_hash, layers_old, layers_new, args.only_different, changed)
  File "/usr/bin/kicad-diff.py", line 439, in DiffImages
    old = pdf2png(old_file, i not in layers_old, new_file)
  File "/usr/bin/kicad-diff.py", line 329, in pdf2png
    assert False
AssertionError
```

The `Cache` directory only contains `PDF` files and no `PNG` files

![image](https://github.com/INTI-CMNB/KiDiff/assets/3458587/663e5c8e-adfd-45d8-933d-9c8d89bbe7b0)

**Comment by set-soft** [comment]
Hi @Kampi !

This is a system configuration issue, I forgot to mention it here, the explanation is in the KiBot docs:

Note that on some systems (i.e. Debian) ImageMagick disables PDF manipulation in its policy.xml file. Comment or remove lines like this: `<policy domain="coder" rights="none" pattern="PDF" />` (On Debian: */etc/ImageMagick-6/policy.xml*)

I'll add a note here.
